### ISSUE TITLE
"We need your review" chrome store link on Firefox

### ISSUE THREAD

**Issue by thatrobotdev** [dailynowco/daily#104]
#### Bug Report

Explanation: On Firefox, in the top right corner, I got a message taking me to the chrome web store saying "We need your review". Since I am on Firefox, it should take me to the firefox extension page.
Reproduce: Open newtab

Version: 2.6.0

Browser version: Firefox Developer 70.0b9 (64-bit)

OS: Microsoft Windows 10 Home, 10.0.17763 Build 17763

**Comment by idoshamun** [comment]
Hi @thatrobotdev,
Thanks for reaching out :)
Basically there are both Chrome and Firefox call to action buttons and they rotate along with others. We thought it might be worth to keep the Firefox in the Chrome version and the opposite in the FF version.
I agree with the issue you raised and we will remove it.

**Comment by idoshamun** [comment]
@all-contributors please add @thatrobotdev for bugs
