### ISSUE TITLE
Bookmarks are deleted after Sign In

### ISSUE THREAD

**Issue by beo99** [dailynowco/daily#106]
I bookmarked up to twenty articles, in order to synchronize them i signed in.
But after Sign In process with Git my Bookmarks vanished.

**Comment by idoshamun** [comment]
Hi @beo99,
It's unfortunate to hear that your bookmarks were lost but I would like to explain how the sync process works.
Only when you create a user for the first time your existing bookmarks get synchronized. If you login to an existing account all bookmarks will be removed and replaced with your user's bookmarks.
Probably in your case you had already an account which caused this situation.

**Comment by beo99** [comment]
Okey, than maybe i did it wrong but it would be nice if there would be a option to include bookmarks when i login with an other browser.

**Comment by idoshamun** [comment]
Yeah you might be right. At least we should warn the user or give an option to import existing bookmarks.
@tsahimatsliah what do you think?

**Comment by tsahimatsliah** [comment]
Hi @beo99 ,

You're right, we need to solve this issue.
So please let me think about how to implement it on our platform.

**Comment by idoshamun** [comment]
Please refer to https://github.com/dailynowco/daily-apps/issues/76 for the actual implementation issue
