### ISSUE TITLE
Hiding posts option does not show

### ISSUE THREAD

**Issue by omryha** [dailynowco/daily#108]
#### Bug Report

Explanation: Hide posts option does not show.
I read on a closed issue that this feature was released in version 2.5. Love your works, been using it from day 1 :)

Reproduce: *Steps to reproduce the bug, if you know them*

Version: 2.7.0

Browser version: Chrome

OS: Ubuntu 18.04.3

**Comment by omryha** [comment]
Found it.

**Comment by idoshamun** [comment]
Thank you for using Daily! I'm glad you found this button :)
