### ISSUE TITLE
Sorting results by the time

### ISSUE THREAD

**Issue by paulz1** [dailynowco/daily#112]
Just start using Daily 2.0.
A little question, sounds silly, but actually I could find how to sort the results by the time. To see the newest articles at the top.

Here, for example, top of my results :

MongoDB Atlas is the most reliable cloud database service available. 
/* PROMOTED BY CODEFUND */

Writing Your Own Changelog Generator with Git
32h ago

Creating a solid Data Science development environment
3h ago

How to Install Docker on Windows 10 Home
2h ago

Predicting NBA All Stars
10h ago

Deploy Machine Learning Web API using NGINX and Docker on Kubernetes in Python
13h ago

Guide to Tomcat Manager Application
10h ago

Data Science Best Practices: Python Environments
28h ago

Designing Your First App in Kubernetes: A Summary
16h ago

Thanks for helping.

**Comment by lewis150193** [comment]
I'll have a crack at this

**Comment by idoshamun** [comment]
Hi @paulz1,
Currently, we provide only one sorting, our unique scoring which takes into account both the time and popularity of the article. In the future, we will add an option to sort by time.
Hopefully, it fulfills your request :pray:

**Comment by paulz1** [comment]
Ok, thank you @idoshamun 
Just to precise a bit this request, I think it could be very useful.
I open "Daily 2.0" occasionally 3-4 times (or more) in a day. It's very important to see if there is something new. For the moment "something new" could be at the line 5th... or 10th, or even on the second page. And so, there are a lot of chances that I never will see this "something new".

So, I agree that priority of this feature is Low, but it could be very useful in the same time.
Thank you very much for your help and for your job.

**Comment by idoshamun** [comment]
@all-contributors please add @paulz1 for ideas
