### ISSUE TITLE
Bug: "The URI you submitted has disallowed characters" error.

### ISSUE THREAD

**Issue by wowkanwowka** [dailynowco/daily#114]
#### Bug Report

Explanation: Scrolling down the page with C++ articles and clicking on almost any of tabs (I haven't tried them all) leads to "The URI you submitted has disallowed characters." error. I tried doing the same on other pages and couldn't reproduce the bug.

Reproduce: Seems to me that scrolling down to 500 line is enough

Version: 2.8.0

Browser version: Chrome 77.0.3865.120

OS: Windows 10.0.17134

URL:
https://isocpp.org/blog/%3Ca%20href=%22https://isocpp.org%27.%27/blog/2019/08/approval-tests-with-clare-macrae-cppcast%22%3EApproval%20Tests%20with%20Clare%20Macrae--CppCast%3C/a%3E

Screenshot:
![image](https://user-images.githubusercontent.com/16153753/67944408-7cbb9580-fbed-11e9-9298-1c1672c3f51d.png)

**Comment by idoshamun** [comment]
Hi @wowkanwowka,
Thank you for for reporting this annoying bug. It was caused by a bug in the isocpp RSS feed which has already been fixed. I fixed the problematic URLs and now it should work perfectly.
Let me know if you still run into problems :)

**Comment by idoshamun** [comment]
@all-contributors please add @wowkanwowka for bugs
