### ISSUE TITLE
🐛 BUG: Companion overlaps/hides some important buttons on the article.

### ISSUE THREAD

**Issue by Sodium727** [dailynowco/daily#1145]
### What went wrong? 🤔

Sometimes, the companion window would **sit on top of a button**, for example a "close ad" button, making it impossible to click that button without **disabling the companion feature then enable it again**. This creates inconvenience. My screenshots are shown below.

What [the page](https://medium.com/@pixie9/convert-png-to-jpg-without-internet-a-diy-guide-e1d985f6d7e0) looks like, there's a button [X]:
![image](https://github.com/dailydotdev/daily/assets/112752505/d909388f-0956-4280-942d-69c06202b5d4)

But the companion window jumps in and destroy everything:
![image](https://github.com/dailydotdev/daily/assets/112752505/9cdca0f8-7088-42cd-959f-1302956dd5ff)

### Steps to Reproduce Issue

```bash
I don't know much about back-end programming, but I hope this gets fixed soon.
```

### Solution Proposed

Maybe make the companion window movable? Or perhaps an option to temporarily hides it.

### Screenshots

```bash
What [the page](https://medium.com/@pixie9/convert-png-to-jpg-without-internet-a-diy-guide-e1d985f6d7e0) looks like, there's a button [X]:
![image](https://github.com/dailydotdev/daily/assets/112752505/d909388f-0956-4280-942d-69c06202b5d4)

But the companion window jumps in and destroy everything:
![image](https://github.com/dailydotdev/daily/assets/112752505/9cdca0f8-7088-42cd-959f-1302956dd5ff)
```

### Environment

Windows 10 22H2; Microsoft Edge 124.0.2478.67 (64-bit)

### Browsers

Microsoft Edge

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @Sodium727,

Thanks for reporting. Closing as it's a dup of https://github.com/dailydotdev/daily/issues/967
