### ISSUE TITLE
XSS attack through article titles

### ISSUE THREAD

**Issue by JohannesBe** [dailynowco/daily#116]
### Bug Report

Explanation: 

XSS injection through article titles

Reproduce:  Make an article with a `<script src="mymaliciousscript.sh/script.js">` and enjoy the data harvesting, or phishing iframe layover stuff. Try to get script confirmed.

Browser version: Firefox Nightly, 72.0a1

OS:  Linux 5.3.8-arch1-1 x86_64 GNU/Linux

![image](https://user-images.githubusercontent.com/21303311/68242344-a40ccb00-0010-11ea-95d1-86cb51b8a64d.png)

![image](https://user-images.githubusercontent.com/21303311/68242405-bb4bb880-0010-11ea-86aa-cdbe247b87c8.png)

![image](https://user-images.githubusercontent.com/21303311/68242430-c69ee400-0010-11ea-932b-d8ee211c2a82.png)

**Comment by idoshamun** [comment]
Hi @JohannesBe,

Thank you very much for dedicating the time to find this major issue.
Security issues are highly important and we strive to fix them as soon as possible.
I already know the root cause of this issue, will apply the fix.

**Comment by idoshamun** [comment]
@all-contributors please add @JohannesBe for bugs

**Comment by JohannesBe** [comment]
@idoshamun thank you for the extremely quick and adequate response, it is seldom that I open up a security issue in a project and that it is handled so smoothly.

**Comment by idoshamun** [comment]
I am glad to hear that you are satisfied with our dedication to our users, I would like to thank you once more for discovering such a major issue. Hopefully, you have already installed version 2.9.0 with the hotfix and a new awesome feature for personalizing the look & feel.

**Comment by JohannesBe** [comment]
I did :) 

![image](https://user-images.githubusercontent.com/21303311/68294406-65b6f080-0090-11ea-8957-ccac22fb3194.png)
