### ISSUE TITLE
Texts getting blurred on mouse hover

### ISSUE THREAD

**Issue by aliforever** [dailynowco/daily#119]
#### Bug Report

Explanation: *Texts on tiles getting blurred on mouse hover*

Reproduce: *Hover on texts*

Version: *2.9.0*

Browser version: *78.0.3904.87*

OS: *Windows 10 x64 Pro 1903*

Before Hover:
![image](https://user-images.githubusercontent.com/14090252/68341789-7605b480-00fe-11ea-8388-c1497a129686.png)

On Hover:
![image](https://user-images.githubusercontent.com/14090252/68341806-7e5def80-00fe-11ea-9039-ea0958071a99.png)

**Comment by idoshamun** [comment]
Hi @aliforever,
Thank you for submitting the issue.
The blurriness is caused due to the scaling transformation the card is going through on hover.
If you would like to cancel this effect, you can open the layout panel using the top left button near the logo and turn off the card animations.

**Comment by aliforever** [comment]
Hi,
Turning off the card animations only works for the caption. not the photos.
It causes a bad experience on long-term use.

**Comment by idoshamun** [comment]
Actually you're right. I forgot that it only disables the photo.
We will rethink this animation and let you know :)

**Comment by sshanzel** [comment]
+1

**Comment by sshanzel** [comment]
I hope this gets high priority, it is actually quite discouraging to look at. But since i love the extension i'm still using it everyday.

**Comment by sshanzel** [comment]
Also, i am more than willing to contribute, just let me know where to start 😁

**Comment by idoshamun** [comment]
@sshanzel I set it now to high priority, hopefully, tomorrow we will be able to address it with a design suggestion.
Once we get the design, I will create a technical issue with a detailed explanation of the new animation.
I will be happy to get your contribution to this one :)

**Comment by sshanzel** [comment]
Sounds great! Looking forward to it! More power to the team!

**Comment by idoshamun** [comment]
@sshanzel I've created a technical issue and I would appreciate your contribution.
I'm available on our Slack community and here as well so feel free to ask questions.
Let me know if you would like to give it a go. Thanks in advance :heart: 
https://github.com/dailynowco/daily-apps/issues/78

**Comment by sshanzel** [comment]
Wow, what a very quick response from the team! <3 I would love to start working with this immediately, and it would be at this coming weekend. I will do my best to provide what is required. Thanks a lot <3

**Comment by idoshamun** [comment]
Thank you for being so active :pray:

**Comment by color-space** [comment]
This can not be a problem of transform itself, maybe use full pixels in your transform

**Comment by idoshamun** [comment]
@color-space thank you for jumping in the discussion and raising your voice.
We used percentages for our hover animation which is probably the reason for the blurry text, and probably your solution will solve this issue.
With that said, we would like to introduce a more elegant and subtle animation rather than the current one,
Hopefully, you will like it :)

**Comment by idoshamun** [comment]
Thanks to @sshanzel for contributing the fix for this issue.
In a few days, I'll release a new version :)
