### ISSUE TITLE
Feature Request: Non-animated Mode/Settings

### ISSUE THREAD

**Issue by jundialwan** [dailynowco/daily#12]
Awesome application!
Great work from the team.

I have a __feature suggestion/enhancement__.

It would be great if it has non-animated mode/settings to disable animation on hover and another animation.

Thank you.

**Comment by idoshamun** [comment]
Hi @jundialwan,

Thanks for the suggestion, may I ask why would you like to turn off the animation?

**Comment by jundialwan** [comment]
Hi @idoshamun,

Sorry didn't post the reason. I think my reason is a little bit personal. I don't know if others have the same problem. 

From my perspective some of the animation, e.g. hover animation, blinking bookmark suggestion animation, is little bit a too much. Other than that is just fine, like sidebar animation. I think simple animation/no animation is better. Because of that reason, I want to disable the animation. I think my suggestion is about personalization. Just like bright/dark theme options, that's great.

Daily is simple yet great idea. I love Daily and I would use it daily ;)

Thank you for considering my input.
Have a nice weekend :tada: :smiley:

**Comment by idoshamun** [comment]
I totally get it, we will consider it in our next roadmap plan. Stay tuned.

**Comment by idoshamun** [comment]
In Daily latest version 1.6.0, we introduced toggle button for reducing the hover animation of the cards.
You have to sign in first.
I hope it suits your needs, enjoy :)

**Comment by jundialwan** [comment]
Fantastic @idoshamun !
Thanks for the update. Really enjoy it!

**Comment by idoshamun** [comment]
Thanks for submitting such a great feedback!
Keep up the good work :)

**Comment by idoshamun** [comment]
@all-contributors please add @jundialwan for ideas
