### ISSUE TITLE
🐛 BUG: The extension consumes too much cpu when a new tab is opened in an external monitor.

### ISSUE THREAD

**Issue by sogyals429** [dailynowco/daily#128]
### What went wrong? 🤔

When a new tab is opened in the browser the app crashes in an external monitor.
![Screen Shot 2019-12-10 at 9 25 19 pm](https://user-images.githubusercontent.com/17468028/70521764-e8513500-1b93-11ea-99b4-454c19c27210.png)

Chrome Task Manager Screenshot
![Screen Shot 2019-12-10 at 9 30 41 pm](https://user-images.githubusercontent.com/17468028/70521998-61508c80-1b94-11ea-825e-ef1d44c49058.png)

### Expected Behavior

Tab should show news articles

### Actual Behavior

Blank Screen is shown with no news articles

### Steps to Reproduce Issue

1. Connect Laptop to external monitor.
2. Open a new google chrome tab on the external monitor.

### Solution

NA

### Environment
Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)

#### Operating System
Mac OS Catalina V.10.15.1 (19B88)
#### Version of Daily
2.10.3
#### Browser
Google Chrome

**Comment by idoshamun** [comment]
Hi @sogyals429,

Thanks for submitting this bug. Actually I use Daily all the time with two external 4k monitors.
I would like to try and understand your situation better, do you use the card view or list view?
Could you please try to kill the extension, delete and reinstall?

**Comment by sogyals429** [comment]
Hi @idoshamun,

i'm currently using the card view layout.
The issue comes up occasionally. I did try killing the extension and reinstalling it.

**Comment by idoshamun** [comment]
One known process that may cause this issue is a quick resizing of the window which we know might cause the app to stuck.
It's important to find a way to reproduce this issue so I can understand how to solve it.
Does it happen only when an external monitor is connected? Could you check the logs in the devtools when it happens?

**Comment by sogyals429** [comment]
yup it happens when the chrome window gets resized quickly. Was able to reproduce the issue again. 
The dev tools doesn't allow to select the screen. I'm guessing it might be an issue with chrome. 
![Screen Shot 2019-12-11 at 7 39 21 pm](https://user-images.githubusercontent.com/17468028/70605237-3a569100-1c4e-11ea-830c-a26cebfc39ff.png)
![Screen Shot 2019-12-11 at 7 39 21 pm](https://user-images.githubusercontent.com/17468028/70605363-7b4ea580-1c4e-11ea-9eec-4d8af905a42b.png)

**Comment by sogyals429** [comment]
Is it something to do with javascript? Is it possible to view the codebase?

**Comment by idoshamun** [comment]
Yes, it has something to do with Javascript. Our code is 100% open and the relevant repo should be https://github.com/dailynowco/daily-apps, it contains all our frontend code.
I suspect it's actually a bug in this library: https://github.com/paulcollett/vue-masonry-css. We use this lib to create our unique card view. I must dive into it as soon as possible.
I would very much appreciate your help :pray:

**Comment by sogyals429** [comment]
Sure. Will try to look into it.

**Comment by idoshamun** [comment]
Thank you so much! I've assigned you to the issue. I'll try to get into it as well.

**Comment by idoshamun** [comment]
@sogyals429 I found the bug! It is actually something inside my `DaLineClamp` component.
I think the quick resizing caused an infinite loop in this component.
I've fixed it now and hopefully release it soon.

**Comment by sogyals429** [comment]
That’s great. Thanks

**Comment by idoshamun** [comment]
Released as part of v2.10.7. Should be available pretty soon.
