### ISSUE TITLE
soshace blog update

### ISSUE THREAD

**Issue by MaryVorontsov** [dailynowco/daily#130]
Hello, have not seen https://blog.soshace.com/ being updated today 12/20 (Dec 20). Last 2 articles are missing from the feed.
Can you check, please?

**Comment by idoshamun** [comment]
Hi @MaryVorontsov,
I can see the last 2 articles from 12/20.
Please see my screenshot:
![image](https://user-images.githubusercontent.com/1993245/71324679-7c06f780-24ea-11ea-86f7-647baaa8c421.png)
