### ISSUE TITLE
🐛 BUG: I am singed out immediately

### ISSUE THREAD

**Issue by mrsideshowjack** [dailynowco/daily#133]
### What went wrong? 🤔

When I sign in (with gh or google) I am singed out immediately

![Screen Recording 2020-01-24 at 11 03 55](https://user-images.githubusercontent.com/9937136/73064701-bcff7c80-3e99-11ea-8c32-c42b32e5ac77.gif)

### Expected Behavior

to stay signed in

### Actual Behavior

I am singed out immediately

### Steps to Reproduce Issue

Signin

#### Operating System

MacOS Cataline v 10.15.2

#### Version of Daily

2.12.3

#### Browser

Chrome Version 79.0.3945.130

**Comment by idoshamun** [comment]
Hi @mrsideshowjack,

Thanks for reporting this issue. Our login system is based on cookies, could it be that your browser blocks cookies?

**Comment by mrsideshowjack** [comment]
It seems so, getting this in the console:
```
A cookie associated with a cross-site resource at https://app.dailynow.co/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
```

**Comment by idoshamun** [comment]
@mrsideshowjack thank you for the clarification.
I should fix it as soon as possible!

**Comment by idoshamun** [comment]
Sorry for the late response, it's my weekend over here so it took me some time.
I believe I fixed this issue. Could you please verify that I'm correct?

**Comment by mrsideshowjack** [comment]
All fixed!
