### ISSUE TITLE
🧩 FEATURE REQUEST: Local Bookmarks

### ISSUE THREAD

**Issue by sadiq1745** [dailynowco/daily#135]
## Feature Request
Just like the feature showing bookmarks from daily, can we please have another feature where the local bookmarks are fetched and displayed on the new tab page.

### Description
Most of us devs bookmark hundreds of pages and hence use various bookmark helper extensions to see/manage them in a new tab. Using daily forces us to use the existing and not-so-friendly-for-long-list bookmark bars or managers inbuilt in browsers. 
Such people (like me) may benefit a lot if daily showed the bookmarks as well.

### Solution

Solution could be to extend the 'Show your bookmarks' toggle button's functionality to have another option which fetches and shows a simple list (or the cards) of local bookmarks.

**Comment by idoshamun** [comment]
Hi @sadiq1745,

Thanks for reaching out!
We are doing our best to deliver value to our users by curating the best dev news but this feature request is out of scope, unfortunately.

**Comment by sadiq1745** [comment]
@idoshamun I get it :) . Anyways thanks for the response.

**Comment by Khalidxx** [comment]
@idoshamun you don't have to fetch and display local bookmarks. An alternative would be to leave the bookmark bar as it is. Currently, the bookmark bar disappears and is replaced by daily.dev content. This happens specifically for Chrome. In Firefox, the bookmark bar is visible alongside the daily.dev content. Can we have the same for Chrome as well?

**Comment by idoshamun** [comment]
Hey @Khalidxx,

Unfortunately, this is not possible. We do not control the bookmark bar whatsoever.
Chrome's behavior is a bit weird in this case and we can't do a thing about it.
We did try because many users asked for it but no solution.

**Comment by Khalidxx** [comment]
Oh that's too bad. Well, thanks for you reply! 🙏
