### ISSUE TITLE
🐛 BUG: `read` class on `posts` is affecting the `border-radius` of the element 

### ISSUE THREAD

**Issue by sshanzel** [dailynowco/daily#136]
### What went wrong? 🤔
I've noticed that when I've already read an article, and i refreshes the app, the `border-radius` for `top-left` and `top-right` are missing. I don't know if what i think is right for the style, but please do let me know. Thanks a lot!

![image](https://user-images.githubusercontent.com/13744167/74088491-8b4cff00-4ab0-11ea-8bd0-d837e5a30d03.png)

### Expected Behavior
`border-radius` should be the same as the others regardless if you've already read it or not.

### Actual Behavior

no `border-radius` is being applied

### Steps to Reproduce Issue

1. Click an article.
2. Go back to the app.
3. Refresh the app.

### Solution

I've inspected the element and removed the `read` class, the `border-radius` came back

#### Browser

Chrome

#### App version
2.12.3

**Comment by sshanzel** [comment]
Hi @idoshamun, i would love to fix this immediately, just let me know if i reported it correctly and, a go signal 😁

**Comment by idoshamun** [comment]
Hi @sshanzel,

Thanks for reporting this issue, unfortunately, I'm not able to reproduce it.
Is there anything else I need to do to reproduce?

**Comment by sshanzel** [comment]
Hmmm, strange. I've uploaded a vid of what's happening to me:

https://drive.google.com/file/d/1yoz6olHEdCl1D0f34rr07bppPjtIxa_4/view?usp=sharing

**Comment by sshanzel** [comment]
Closed the issue as it seems to be a rare case on my end only.
