### ISSUE TITLE
🧩 FEATURE REQUEST: Enable to paste URL when Request source

### ISSUE THREAD

**Issue by gilcrespo** [dailynowco/daily#137]
## Feature Request
Right now, it is not possible to use the command CTRL+V to paste a URL to Request source field.

### Description
I think this hability would help the user interation instead to type all the URL and increasing a lot the chance of error.

**Comment by sshanzel** [comment]
This actually works on me.

**Comment by gilcrespo** [comment]
I'm working with Linux OS and using Chromium browser. I'll test more on normal chrome and on friend's windows OS

**Comment by sshanzel** [comment]
I can be the friend on windows. As i am using Windows 😄

**Comment by gilcrespo** [comment]
Sorry about that .. It worked very well after restarting browser. My bad

**Comment by sshanzel** [comment]
No worries, that's all good and normal 😁

**Comment by idoshamun** [comment]
I'm glad to see @sshanzel was able to help and resolve this issue.
Thank you both!
