### ISSUE TITLE
🧩 FEATURE REQUEST: Simplify resetting current search.

### ISSUE THREAD

**Issue by marek-kramski** [dailynowco/daily#138]
## Feature Request
Reset search button.

### Description

Currently, when user searches through articles, there is no easy way of going back to "normal" state. You have to either enter the search input again, clear it and press enter, or refresh the page. 

### Solution

Right now, there is an **x** button that enters the input and clears it, but I think it would be better if its purpose was resetting current search.

### Alternate Solutions

Alternatively, the **x** button can still work like it does now, but leaving the just-cleared, empty input could take us back to unfiltered articles.

**Comment by idoshamun** [comment]
Hi @marek-kramski,
I appreciate you dedicating the time for submitting this feature.
If you click on the Daily logo at the top left corner, it should reset the search.

**Comment by sshanzel** [comment]
I think we can add this on our Vim Navigation feat by using `esc`? :grin: 

So we then navigate again. I mean i think it is intuitive to go back to navigating when you finished your search after hitting `/`.

**Comment by idoshamun** [comment]
I totally agree. Let's try it out :)

**Comment by sshanzel** [comment]
As always, will immediately work on it once the technical issue is up! :grin:

**Comment by idoshamun** [comment]
@sshanzel, here you go:
https://github.com/dailydotdev/daily-apps/issues/91

Thank you once more :heart:

**Comment by sshanzel** [comment]
At your service! From 2019 and beyond! 😁
