### ISSUE TITLE
Clicking on the "Contact" link on the Website opens a new tab

### ISSUE THREAD

**Issue by SevketYALCIN** [dailynowco/daily#16]
#### Bug Report

Explanation: On https://www.dailynow.co/ , the contact link in the menu has a target="_blank" attribute and opens up a new tab on click.

Reproduce: Click on the 'Contact' link in the menu

Version: 1.6.0

Browser version: 68.0.3440.75 (latest)

OS: Windows

**Comment by idoshamun** [comment]
@SevketYALCIN thanks for letting me know, already fixed the issue :)

**Comment by idoshamun** [comment]
@all-contributors please add @SevketYALCIN for bug
