### ISSUE TITLE
Extension is taking high CPU usage

### ISSUE THREAD

**Issue by teja463** [dailynowco/daily#18]
#### Bug Report

Explanation: Whenever i open a new tab, my CPU utliization shoots up and reaches almost 98-100%. It reamins in the same position till I open a webpage in that tab or close that tab. It does not happen when i select list mode. It happens only for thumbnail view.

Reproduce: Install the extension, open a new tab and see the CPU utliization. Close the tab and see the same again.

Version: *Daily version (can be found in Chrome's extension page)*

Browser version: 68.0.3440.106

OS: Window 7

**Comment by idoshamun** [comment]
@teja463 I can confirm your issue after some checks that I did on my PC.
Resolving this issue requires a deeper research but we will take care of it as soon as we can :)

BTW, if you can update the title to something more indicative as it is a CPU issue not memory.

Thanks for reporting!

**Comment by teja463** [comment]
Thanks @idoshamun updated the title

**Comment by idoshamun** [comment]
Hi @teja463,

Your bug report was actually one of the most challenging issues we had to deal with.
We compare our performance to other image oriented websites like Giphy and we share the same problems.
The main thread is idle and the rasterization threads work very hard to paint the images especially the gifs. Unfortunately there is no way to change the rasterization process so what we had to do is to remove from DOM all invisible elements and attach them back again when they enter the viewport.
We released version 1.8.3 with this fix please update and share your thoughts.

I am closing the issue for the time being, please reopen if necessary.

**Comment by idoshamun** [comment]
@all-contributors please add @teja463 for bug
