### ISSUE TITLE
Button to report broken links?

### ISSUE THREAD

**Issue by Jaydelyn** [dailynowco/daily#19]
#### Feature Suggestion

I would love to see a button for reporting broken links which would also remove the link from view. Today I found an article that I was very interested in reading (Programmatically create images with the CSS Paint API, from SitePen, but the link is dead, and I can't find the article via a search engine, either.  Frustrating!

Otherwise, I really love Daily Now!
Thanks!

**Comment by idoshamun** [comment]
Hi @Jaydelyn,

First of all, thanks for sharing your feedback, it is highly appreciated!
I have tried to hunt down this article for you but I think the publisher just removed :(

We are processing almost 100 posts every day so I guess it's time to let the community flag broken posts for whatsoever, it's already way more than we can handle manually as a team.
We will prioritize this feature request but it will still take some time, we have a nice surprise up ahead so stay tuned.

By the way, I would love to have a quick call to hear more ideas and thoughts.
If you are up to it, just ping me ido@elegantmonkeys.com

**Comment by idoshamun** [comment]
Hi @Jaydelyn, Daily 2.0 is released and now you can report NSFW and broken link posts. Just remember that you have to sign up before.

**Comment by Jaydelyn** [comment]
That's great news, thanks so much!

**Comment by idoshamun** [comment]
@all-contributors please add @Jaydelyn for ideas
