### ISSUE TITLE
Add to Blacklist

### ISSUE THREAD

**Issue by bm-stschneider** [dailynowco/daily#20]
#### Feature Suggestion

Add some kind of blacklist/filter feature where you block certain blogs to appear.

**Comment by idoshamun** [comment]
Hi @bm-stschneider ,
First of all, thanks for sharing your feedback with us. It is highly appreciated.
Turning on/off blogs is an already existing feature, if you move your mouse to the left side a side menu will appear with a list of all the blogs and you can just click on them.

Please let me know if this is what you asked for

**Comment by bm-stschneider** [comment]
Ah okay I thought this is for just filtering the current view for those entries. Yes that does suffice

**Comment by idoshamun** [comment]
With your permission I would like to close this issue
