### ISSUE TITLE
Show scrollbar on left sliderbar menu

### ISSUE THREAD

**Issue by vishalksuthar** [dailynowco/daily#21]
We are looking for all kinds of feedback and we created a template for almost all of them.
Fill only the relevant section to your issue and delete the other sections, if you can't find a relevant section feel free to go freestyle.

#### New Blog Suggestion

Name:Show scrollbar on left sliderbar menu

Link: *URL to the blog*

Topic: Show scrollbar on left sliderbar menu

#### Feature Suggestion

show scrollbar on left sliderbar menu,becuase currently we need to scroll down using mouse roller or hover on menu and press down arrow key to down. if scrollbar visiable that time we can able to slide down using mouse left click. 

#### Bug Report

Explanation: *Describe the bug as accurate as possible*

Reproduce: *Steps to reproduce the bug, if you know them*

Version: *Daily version (can be found in Chrome's extension page)*

Browser version: *Your browser version*

OS: *Your operating system including version*

*Please add screenshots if possible or any other information that can help fixing the bug*

#### Feedback

*Share with us your thoughts about Daily, positive and negative as one*

![image](https://user-images.githubusercontent.com/43471370/45916059-32f66c80-be7d-11e8-8535-dc30b0e32730.png)

**Comment by idoshamun** [comment]
Hi @vishalksuthar, I'm glad to announce that Daily 2.0 is released with a scrollbar on the sidebar

**Comment by idoshamun** [comment]
@all-contributors please add @vishalksuthar for ideas
