### ISSUE TITLE
Please include a functionality to search for the articles from a particular source or to filter out the sources like from the sidebar. 

### ISSUE THREAD

**Issue by Gsbansal10** [dailynowco/daily#22]
We are looking for all kinds of feedback and we created a template for almost all of them.
Fill only the relevant section to your issue and delete the other sections, if you can't find a relevant section feel free to go freestyle.

#### New Blog Suggestion

Name: *Name of the blog*

Link: *URL to the blog*

Topic: *Main topic of the blog*

#### Feature Suggestion

*Describe your feature and explain why you need it*

#### Bug Report

Explanation: *Describe the bug as accurate as possible*

Reproduce: *Steps to reproduce the bug if you know them*

Version: *Daily version (can be found in Chrome's extension page)*

Browser version: *Your browser version*

OS: *Your operating system including version*

*Please add screenshots if possible or any other information that can help fixing the bug*

#### Feedback

*Share with us your thoughts about Daily, positive and negative as one*

**Comment by idoshamun** [comment]
Hi @Gsbansal10, Daily 2.0 is out now and it comes with a lot of customizations as you requested. Feel free to reopen this issue if not
