### ISSUE TITLE
Add Search bar

### ISSUE THREAD

**Issue by hasarmu** [dailynowco/daily#23]
Add Search bar in Daily now. if i switch fullscreen mod then i can't see search bar in new tab! nor i can't search via ctrl + l keyword!

![daily](https://user-images.githubusercontent.com/30354517/46580725-33c9f980-ca4c-11e8-963c-ab285480ab1f.PNG)

**Comment by idoshamun** [comment]
Just wanted to let you know that currently we will not add a search bar to the extension
