### ISSUE TITLE
Provide a way to filter post from single or multiple blogs/sources

### ISSUE THREAD

**Issue by nmrony** [dailynowco/daily#24]
#### Feature Suggestion

It would be great to have a way to filter posts from single or multiple blogs/sources. It is tedious to switch off all blogs from list except the post I want to read from.

**Comment by idoshamun** [comment]
@nmrony thanks for reaching out, I am much obliged reading about this feature.
We are already planning releasing this feature as part of a new major version.
Please bare in mind that it can take a while until we launch :)

**Comment by idoshamun** [comment]
Hi @nmrony, Daily 2.0 is out now and it's packed with a new tag based filtering and the ability to view a single source or a single tag as a temporary filter. Hope it helps, please reopen the issue otherwise
