### ISSUE TITLE
Auth prompts for unnecessary sign in

### ISSUE THREAD

**Issue by f1tech** [dailynowco/daily#26]
Bug Report

Explanation: When I attempt to sign in I am asked to enter my credentials even though I am already signed in on both Google and github. In inspecting the auth dialogs it appears that they are authentic, but this is a common phishing scheme, so I think it discourages creating an account.

Reproduce: 
1. Click the sign in button
2. Click either the Github or the Google button. 
Version: *Daily version (can be found in Chrome's extension page)*

Browser version: Chrome Version 70.0.3538.102

OS: Mojave 10.14.1

#### Feedback

I love this resource. I do have to say that it seems that over the last couple of weeks the quality of curating has declined. There have been a number of pieces that are just marketing and there are too many soft skill articles, some that don't even seem to apply to developers. "The Start Up" in particular provides way too many articles that I don't think are of interest or provide value to developers.

**Comment by idoshamun** [comment]
Hi @f1tech, now that Daily 2.0 released this issue has been fixed. We managed to find a way to do the login without opening a popup window as suggested by Chrome.
