### ISSUE TITLE
Request to support Brave browser "ON START UP, OPEN NEW TAB PAGE"

### ISSUE THREAD

**Issue by artoodeeto** [dailynowco/daily#27]
#### Feature Suggestion
Hi Dev team, I wanted to ask about the feature "ON STARTUP, OPEN NEW TAB PAGE" like on google chrome to be added on Brave browser. So, on google chrome when I open a new tab, your page will be the default, but on brave browser, you don't have that option.

**Comment by idoshamun** [comment]
Hi @artoodeeto,

Thanks for approaching :)
Currently, we do not officially support the Brave browser, we have to look into it to understand its capabilities.
Please note that it will take some time as we are focused now on improving the current experience in Chrome and Firefox.

**Comment by artoodeeto** [comment]
@idoshamun no problem sir. do you have a mailing list for any updates?

**Comment by idoshamun** [comment]
@artoodeeto We use our Twitter account (https://twitter.com/dailynowco) and Slack (https://slack.dailynow.co/) to announce new features or versions to our users :)
Feel free to join or follow

**Comment by artoodeeto** [comment]
@idoshamun thank you. ill close this. :)
