### ISSUE TITLE
Feature Request: Ability to filter posts 

### ISSUE THREAD

**Issue by Esteban-Rocha** [dailynowco/daily#28]
I think something like `Pinterest` do; For example `Codementor` has some great articles but there are some of them that are utterly irrelevant and plain noisy so they only add clutter on the daily feed, so we should have the option to mark to see "less" of those kind of posts, for some weeks now I have seen more and more irrelevant and plain dumb posts and articles so we should be able to at least configure some filtering without having to disable for complete a source.

**Comment by idoshamun** [comment]
Hi @Esteban-Rocha,

Thanks for reaching out and highlighting this issue.
We are working hard to add tags/topics based filter to the feed so as you suggested you can see only relevant posts and filter out content which you don't like.
Hopefully it will solve this issue you raised :)

Please stay tuned!

**Comment by idoshamun** [comment]
Hi @Esteban-Rocha, we have just released Daily 2.0 with tag based filtering so you can remove irrelevant content from your feed
