### ISSUE TITLE
Feature Request: Custom sources

### ISSUE THREAD

**Issue by UsamaAmjad** [dailynowco/daily#29]
#### Feature Suggestion

Custom Sources: It would be great if I can add my own list of blog sources or somehow can set the area of my interest for example Design, Engineering, and Development. 

#### New Blog Suggestion

Name: *Netflix Technology Blog*
Link: *https://medium.com/@NetflixTechBlog*
Topic: *Software Engineering*

Name: *Airbnb Design*
Link: *https://medium.com/airbnb-design*
Topic: *UI/UX/Design*

Name: *Airbnb Engineering*
Link: *https://medium.com/airbnb-engineering*
Topic: *Software Engineering*

**Comment by idoshamun** [comment]
Hi @UsamaAmjad,

Thanks for reaching out here and submitting your review on Chrome Web Store.
We are working now on a brand you version with much more advanced filtering so you will be able to adjust your feed according your interests and suggest new sources easily as you suggested.

Regarding the blogs we already have netflix and airbnb eng. on our list so you can enjoy them.
I'll take a look on airbnb design as well and let you know :)

Thanks again!

**Comment by idoshamun** [comment]
I am closing this issue as all these blogs are in Daily already as of today :)
