### ISSUE TITLE
infinity tab features and online profile features

### ISSUE THREAD

**Issue by Smssyed8** [dailynowco/daily#30]
features request 
1. features of Infinity tab extension( to add notes, to dos, side view of bookmarks, new background each time, shortcut keys) 
2. view coding challenges, opportunities at one place.
3. Increase my online profile by coding daily.
4. online coding compilers to be displayed.
5. skills update etc.

These features are one i am waiting at one place. will be lot helpful. love ur extension

**Comment by idoshamun** [comment]
Hi @Smssyed8,

Thanks for sharing your feedback :)
We plan a major release soon and then we will decide the new roadmap and will take your suggestions into consideration.

In the meantime, feel free to rate us in the store and help us grow :)
[Chrome Store](https://chrome.google.com/webstore/detail/daily-source-for-busy-dev/jlmpjdjjbgclbocgajdjefcidcncaied)
[Firefox Store](https://addons.mozilla.org/en-US/firefox/addon/daily/)

**Comment by thenathurat** [comment]
Dear Daily team, I am really dissapointed there's no Vue.js hashtag.

@idoshamun since there is React, and Angular, there also should definitely be Vue.js. Or perhaps javascript frameworks in general.

**Comment by idoshamun** [comment]
Hi @thenathurat, I totally agree with you as Daily is written in Vue. 
Tags are automatically created based on the content, this is a hint for me that probably we don't have enough sources about Vue. 
If you know any high quality blog please share the link with me and I will add them.

**Comment by thenathurat** [comment]
This one is high quality - https://news.vuejs.org/

This looks high quality as well - https://vuejsfeed.com/ or perhaps https://vuejsfeed.com/category/News

**Comment by idoshamun** [comment]
Thanks! I will add it to our upcoming source list

**Comment by thenathurat** [comment]
Ok, awesome. When can we expect them to appear in the sources list?

**Comment by idoshamun** [comment]
In the upcoming days probably, it usually doesn't take long. Just some design work to adjust the source logo

**Comment by idoshamun** [comment]
vuejsfeed is live on Daily

**Comment by thenathurat** [comment]
Hi @idoshamun, one more thing - if Daily is to save devs as much time as possible, then I say we need to see when the next release of our used software is, and what does it bring.

Now, I don't know whether GitHub API allows for that, though anyway I see it as a **crucial** feature.

**Comment by idoshamun** [comment]
Hi @thenathurat, 

Could you elaborate a bit how you imagine this feature?

**Comment by thenathurat** [comment]
@idoshamun just as news appear in the app, new releases can as well. Just as articles do, but perhaps looking differently. You'd have to subscribe to different frameworks; by default you wouldn't know about any new release from the app.

**Comment by idoshamun** [comment]
Do you know where we can this information from?

**Comment by thenathurat** [comment]
From GitHub, for example.

**Comment by thenathurat** [comment]
Also, official blogs usually mention new releases.

**Comment by idoshamun** [comment]
We have some official blogs in Daily but we can add more
