### ISSUE TITLE
First Thing That Needs To Be Done

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [dailynowco/daily#33]
1. show info based on relevance & frequency of the multiple sources the info aggregation is getting the info from

- so if **python 3.0** is in 100% of all the sources, then i'll be worth showing

2. **highlights key terms** such as the subject like companies, names, places, etc.
so that the info is easily scannable

the media always did nothing but complained about info-overload for years, instead of valueless info, actually make things better and do something good

**Comment by idoshamun** [comment]
Hi @SolveAllProblemsRightNow ,

Thanks for reaching out, unfortunately I am not sure I totally understand you.
Could you please elaborate what you mean so I can help?

**Comment by SolveAllProblemsRightNow** [comment]
what exactly and specifically do you need more explaining
