### ISSUE TITLE
Create an endpoint for shields.io badge

### ISSUE THREAD

**Issue by nimishjn** [dailynowco/daily#339]
There is a feature in the website [shields.io](https://shields.io) where we can create custom badges using an endpoint. 
The endpoint should basically return a JSON like the one given below:
```
{
  "schemaVersion": 1,
  "label": "DAILY.DEV",
  "message": <Number of articles read in string format>,
  "color": <Color depending on the level>
}
```
There can be a simple endpoint like `<endpoint URL>?user=nimishjn` which will return the JSON data depending on the username. Developers can use this custom shields.io badge for their GitHub README.md
Check [this](https://shields.io/endpoint) link for more info.

#### Diamond level: 
```
{
  "schemaVersion": 1,
  "label": "DAILY.DEV",
  "message": "150",
  "color": "#56bdf0"
}
```
![image](https://user-images.githubusercontent.com/63140632/137782770-97e4f7ff-4e5e-48a4-b863-4a8e8e3c087c.png)
#### Platinum Level: 
```
{
  "schemaVersion": 1,
  "label": "DAILY.DEV",
  "message": "150",
  "color": "#ab6af2"
}
```
![image](https://user-images.githubusercontent.com/63140632/137782330-3e65a6c7-3f44-441f-928f-06be53334fda.png)

**Comment by McJoe21** [comment]
Header for php endpoint
