### ISSUE TITLE
Escort service post

### ISSUE THREAD

**Issue by f1tech** [dailynowco/daily#34]
While the model in the picture is indeed lovely, I'm sure you don't intend to promote an escort service here.

A link from the low-quality echo js is currently doing just that.

**Comment by idoshamun** [comment]
Hi @f1tech,

Thanks for reporting this issue, I already taken care and remove this post.
I will investigate how this post passed our NSFW moderation system and fix this bug.

**Comment by JMente** [comment]
Bug isn't fixed escort post continue showing from echo js

**Comment by idoshamun** [comment]
Hi @JMente,

Thanks for reporting, as soon as I saw your comment I deleted these posts.
I will look further how to fix this issue, sorry for this :(

**Comment by JMente** [comment]
Hi @idoshamun  

if you allow me, I could suggest deleting echo js until solving the problem it is very possible that it is a safety inconvenience of them and not of your application

**Comment by idoshamun** [comment]
This is good idea indeed but the problem is that people love the content from echojs and it gets very popular usually. Maybe I should discuss with them.

**Comment by JMente** [comment]
Well, another solution could be to filter everything that contains the word `" escort", " escort ", "escort "` in the title

**Comment by idoshamun** [comment]
Yeah that's what I have in mind as well, currently the moderation system
only takes images into account

**Comment by idoshamun** [comment]
@JMente I uploaded a fix as suggested, hopefully we will not see these nasty posts anymore
