### ISSUE TITLE
Where can I search history ?

### ISSUE THREAD

**Issue by RoyiNamir** [dailynowco/daily#35]
I saw an interesting article few days ago and now i cant see it

is there a search feature for history ???

**Comment by idoshamun** [comment]
Hi @RoyiNamir,

Currently there is no search feature :(
We are about to launch Daily 2.0 with bunch of awesome new features and other surprises, you can subscribe for updates here:
https://www.producthunt.com/upcoming/daily-2-0

Search feature is totally on our roadmap so stay tuned :)

**Comment by RoyiNamir** [comment]
TODA
