### ISSUE TITLE
Feature Request: Top Products (Producthunt) 

### ISSUE THREAD

**Issue by code-monk08** [dailynowco/daily#36]
#### Feature Suggestion
It would be great if all development related products/tools are also listed as cards in the extension, as featured on Product  Hunt on everyday basis.

**Comment by idoshamun** [comment]
Hi @code-monk08,

Great idea! I will dive deeper to see if Product Hunt has some tag based RSS feed.
Stay tuned :)

**Comment by code-monk08** [comment]
sure @idoshamun :+1:

**Comment by idoshamun** [comment]
@code-monk08 Product Hunt is now available on Daily :)
