### ISSUE TITLE
Feature Request: Easier Way to Submit Suggested Blogs

### ISSUE THREAD

**Issue by DaveyJake** [dailynowco/daily#37]
#### Feature Suggestion: Easier Blog Suggestion Submission

There needs to be an easier way to submit blog suggestions from the home screen.  Something with just 3 `input` fields: `Title`, `URL`, and `Description` and the `submit` button.

<hr />

#### New Blog Suggestion

**Name:** PixelHours

**Link:** https://pixelhours.com/

**Topic:** Curated visual bookmarks collection for designers & developers.

<hr />

#### New Blog Suggestion

**Name:** Unheap

**Link:** http://www.unheap.com/

**Topic:** A tidy repository of Javascript and jQuery plugins.

<hr />

#### New Blog Suggestion

**Name:** WP Plugin Directory

**Link::** http://wpplugindirectory.org/

**Topic:** A smarter way to find WordPress plugins

**Comment by idoshamun** [comment]
Hi @DaveyJake,

Thanks for sending these blog suggestions, I will go through them and let you know.
Regarding the feature suggestion, just stay tuned Daily 2.0 is almost here and totally addresses this issue ;)

**Comment by idoshamun** [comment]
Now you can suggest blogs right from Daily :)
