### ISSUE TITLE
Feature Request: Easier to see new articles

### ISSUE THREAD

**Issue by dmpinder** [dailynowco/daily#39]
#### Feature Suggestion

It would be great if it was possible to either see new articles since I list viewed Daily (e.g. a nice red NEW tag on each new article) or a way to mark as "read" what is already there (perhaps make them semi-opaque) so it's easier to spot new articles. 

It would also be amazing to have a #php and #wordpress tags, as these are my main areas.

Thanks!

**Comment by idoshamun** [comment]
Hi @dmpinder,

Thank you for submitting this feature, I believe it can improve the experience of other users as well.
Let me discuss about it with the team, I'll keep you posted.

Regarding the tags, they are automatically created based on the content we gather. It might be that we don't have enough php and wordpress oriented content. If you can share some high quality sources so we can add to our list and then these tags might show up :)

**Comment by dmpinder** [comment]
Hi @idoshamun,

Thanks for the reply and taking the requests onboard! I'll be sure to submit some good PHP / WP content soon!

Thanks!

**Comment by idoshamun** [comment]
You bet! Let's leave this issue open until we will launch it :)

**Comment by ZviKarp** [comment]
> It would be great if it was possible to either see new articles since I list viewed Daily (e.g. a nice red NEW tag on each new article) or a way to mark as "read" what is already there (perhaps make them semi-opaque) so it's easier to spot new articles.

A more subtle version could be to add to the top corner of the article card a how huch time ago the article was published on daily ( `3h` , `38m` , `16h` ) only if it is less then 24 hours maybe also only on hover.

**Comment by idoshamun** [comment]
Thank you @ZviKarp for the great idea. @tsahimatsliah what do you think?

**Comment by tsahimatsliah** [comment]
I think it's a great idea!
Let me think about it and how we can implement it in the design.

stay tuned!

**Comment by idoshamun** [comment]
https://github.com/dailynowco/daily-api/pull/26 adds a read property to every post received from the server. Besides adding the date to the post we will also design differently posts that you have already read.

**Comment by idoshamun** [comment]
Check out version v2.7.0 :)

**Comment by idoshamun** [comment]
@all-contributors add @zvikarp, @dmpinder for ideas
