### ISSUE TITLE
News Suggestion

### ISSUE THREAD

**Issue by chinchang** [dailynowco/daily#40]
Hi, wanted to send over a link suggestion for your news.

CSSBattle - https://cssbattle.dev
This is the first ever code-golfing game for CSS lovers!
Started a month ago and has over 17K players already.

**Comment by idoshamun** [comment]
Hi @chinchang,

Thanks for submitting this suggestion!
I can't find a blog in this very cool website, what was your original thought?

**Comment by chinchang** [comment]
Oh, I thought it was just about web dev related websites, Sorry. We are launching the blog in a day or two. I'll update the link here

**Comment by chinchang** [comment]
Here is our new blog -> https://cssbattle.dev/blog
Interesting articles on CSS coming up

**Comment by idoshamun** [comment]
Congratulations for launching the blog!
Please remind me again in a few months when it will have more content :)

**Comment by omryha** [comment]
Great tool, I'm using it daily and it's very helpful.
I think people who are interested in other fields rather that CS would be happy to have a tool like this too.
