### ISSUE TITLE
Feature request -- Google Doodle

### ISSUE THREAD

**Issue by denniseh** [dailynowco/daily#42]
#### Feature Suggestion

*Describe your feature and explain why you need it*
Would love to still see the google doodle as a snapshot in a panel.

#### Feedback

*Share with us your thoughts about Daily, positive and negative as one*
This is a great tool! Love it.

**Comment by idoshamun** [comment]
Hi @denniseh,

Thanks for sharing this idea and feedback :)
Do you know by any chance if Google provides an API to get the doodle?

**Comment by idoshamun** [comment]
I tried to look for the Doodle's API but couldn't find any.
I am closing the issue for now as I can't see any way to make it happen :(
