### ISSUE TITLE
C#? SQL? Entire .NET ecosystem? Angular? Tags need some work.

### ISSUE THREAD

**Issue by stamminator** [dailynowco/daily#43]
The selection of available tags has some serious problems. How is it possible to have a developer-focused space with no tags for [the most popular technologies](https://insights.stackoverflow.com/survey/2019#most-popular-technologies) (SQL, shell languages, C#, etc.) and frameworks (Angular, jQuery, .NET, etc.) but plenty of tags for things like `startup`, `entrepreneurship`, `business`, and `life-lessons`? How do `psychology` or `inspiration` fit in here? Do there seriously need to be redundancies like `technology` and `tech`, or `development`, `software-development`, `programming`, and `coding`?

The duplicates should be consolidated, the Pinterest tags need to go away, and useful tags that reflect real-world tech need to be added.

**Comment by idoshamun** [comment]
Hi @stamminator,

Thanks for reaching out with this important feedback!
I highly agree with you, tags need more work and we are doing our best to improve this mechanism.
Basically our content pipeline extracts automatically the tags from the article (based on SEO, medium tags, etc). This is kind of tricky to do as it opens up the tags mechanism to a lot of noise.
We are trying to reduce this noise as much as possible and to consolidate it. If you know any tags that need to be merged list it here, please.

**Comment by idoshamun** [comment]
I did a little work to organize the tags better, check out the tags now and please know that you can also search for tags. Looking forward to your feedback

**Comment by stamminator** [comment]
Thanks for the quick reply. They're looking a bit better. I was able to find `sql` and `angular` this time, but there are still a lot of major players missing. I would suggest having some lists to establish a baseline of tags that should appear. These lists can also be used to fix some of the duplicate tags (i.e. `web-dev` and `webdev`).

**Comment by idoshamun** [comment]
I went over the tags again and fixed more duplicates, hopefully it is better now.
Unfortunately, I cannot create new tags as they are based on the content we gather.

**Comment by sheldonhull** [comment]
How do I request new tags? I wanted to specifically gather some tags for `#powershell` and `#sqlserver` for example.

**Comment by idoshamun** [comment]
Hi @sheldonhull, you can't ask specifically for tags as they are automatically fetched from the articles. You can suggest sources that contain relevant content and then the tags will be created
