### ISSUE TITLE
FEATURE REQUEST: RSS Feed reader & Manager, FEEDBACK: Positive

### ISSUE THREAD

**Issue by dconnolly95** [dailynowco/daily#44]
#### Feature Suggestion

Daily is the first thing I see when I wake up each morning - the computer opens my browser at 9:00 AM automatically, and I see the stories and articles Daily has prepared... **AWESOME!**
Following reading selected stories each day, I'm usually on my way to check my subscribed subreddits and other news sites... This has got me thinking, "wouldn't it be awesome if Daily could _somehow_ integrate even a basic RSS management & feed reader ability?"

This would be without a doubt the greatest addition, meaning more time spent using the Daily extension, with less stops to different sites made every time I open the browser.

#### Feedback

Daily is hands-down the best new tab I have ever used - always got relevant, good content to read, looks **AWESOME** in dark mode, and no intrusive ads or banners - BRILLIANT! I've set it up on all of my development machines, and have even set up a different set of tags at work! Anyone working on the Daily project should be patting themselves on the back right now 😎

**Comment by idoshamun** [comment]
Hi @dconnolly95,

You really made my day!!! One of the best feedback we received so far.

Currently as you know we do not support local RSS, I will raise it up in our next product planning.
In the meantime, let me know if you have any RSS that you would like to see in Daily :)

Thanks again
