### ISSUE TITLE
Filter articles with paywall in medium.

### ISSUE THREAD

**Issue by Shermayster** [dailynowco/daily#45]
#### Feature Suggestion

It's annoying to click on a link and see medium's paywall

**Comment by idoshamun** [comment]
Hi @Shermayster,

Thanks for sending this feature suggestion.
I totally agree, I hate Medium's paywall but as of today I could not find a way to detect it in a reasonable matter.
If you have any idea feel free to share :)

**Comment by idoshamun** [comment]
Until there will be a concrete way to detect Medium's Paywall articles, I close this issue

**Comment by idoshamun** [comment]
Good news! Refer to #57, we basically filter out all Medium's paywall articles since yesterday

**Comment by unm4sk1g** [comment]
Hello,

today I noticed some of the stories that are member-only on Medium still show up. Is there any way we can detect them? One thing I found specific about Member-only stories is the star icon (svg with `star-15px_svg__svgIcon-use`). Maybe you could use this to detect member-only stories?

**Comment by idoshamun** [comment]
Hi @unm4sk1g,

I noticed this issue as well :cry: 
Currently, we detect them by looking for the star icon as you mentioned (see here https://github.com/dailynowco/daily-functions/blob/master/crawler/rules.js#L90). This method does not cover all the cases as we can see and I wonder what are the other possibilities. Maybe Medium serves different pages based on User Agent or other parameters.
I am open to any ideas as I would like to solve it and get rid of the paywall content.

**Comment by unm4sk1g** [comment]
Okay, looks like they add a class called `meteredContent` to the **article** tag when there's a potential paywall to the story. Maybe we could try to avoid them with this?

I've checked few articles that are member-only and they contain that class on article tag, while the one that's not member-only doesn't.

But looks like a temporary solution, since Medium will probably patch that as well to avoid extensions like this one 😢

**Comment by idoshamun** [comment]
It's a good starter. I'll check it out as soon as I can.

**Comment by idoshamun** [comment]
@unm4sk1g, I added to our pipeline another check according to your idea :)
https://github.com/dailynowco/daily-functions/commit/c38e762d322939c4177e621b5d751953f7287b4d#diff-d107350276cefb11d3866f97295a11a6R150
