### ISSUE TITLE
✨ Ability to turn off daily for some time or introduce a silent mode

### ISSUE THREAD

**Issue by zd-zero** [dailynowco/daily#54]
### Problem 
Daily curates the topics that grab the attention of the developers, by having this on every new tab it is hard to focus on the current task at hand.

### Proposed Solution
Either having an option to turn off the _daily_ extension for a given time or provide a way to reduce the noise which we can toggle between modes wherein instead of showing all the news we could have some motivational quotes, wallpaper, a todo task or anything that would be static what not.

**Comment by idoshamun** [comment]
Hi @zd-zero,
Thank you for reaching out :)
Let me discuss it further internally and get back to you on this one.

**Comment by idoshamun** [comment]
After discussing with the team, we decided to accept this great idea :)
We are now waiting for designs from @tsahimatsliah.
When the time comes, are you up to the challenge of contributing this one? We will guide you through and help you nail it

**Comment by zd-zero** [comment]
Great!
> When the time comes, are you up to the challenge of contributing this one? We will guide you through and help you nail it.

I'd love to, I'll work on reading some of the documentation and try to set up the project during my free time. Thanks

**Comment by tsahimatsliah** [comment]
Yehhhhh,

Thank you for helping our community... we appreciate that! 🙏
In addition, now I'm working on the UI/UX of this feature so I'll be in touch very soon.

🤩

**Comment by idoshamun** [comment]
I started to think about the solution and basically as long as we would like to "turn off" Daily, the extension should redirect the user to `https://www.google.com/_/chrome/newtab` before it boots up. This is possible using vue router guards, the same way we do the on-boarding process.

**Comment by idoshamun** [comment]
@zd-zero everything is ready for you to start working on this feature. All details can be found here:
https://github.com/dailynowco/daily-apps/issues/14
I'm available also on Slack so you can send me direct messages (http://slack.dailynow.co/) if you have any question.
Once confirmed we will also send invitation to InVision to see more accurate and interactive design.
