### ISSUE TITLE
Feature Request: Exclude tags

### ISSUE THREAD

**Issue by chimon2000** [dailynowco/daily#55]
We are looking for all kinds of feedback and we created a template for almost all of them.
Fill only the relevant section to your issue and delete the other sections, if you can't find a relevant section feel free to go freestyle.

#### Feature Suggestion

*Describe your feature and explain why you need it*

I need the ability to filter out tags that I am not interested in.  For instance, I may be interested in Development but I may not want to read articles about doing development in Java if I specialize in Node.js.    So I would expect when I exclude the Java tag, anything that was tagged with Java and Development would be excluded from my feed.

**Comment by idoshamun** [comment]
Hi @chimon2000,
Thank you for sharing your ideas with us :)
Have you tried choosing only the tags you like? The development tag might be too wide for you, you can choose the nodejs tag or javascript for example.

**Comment by chimon2000** [comment]
Yes I have, but I still get articles outside of that range. I assume that if I say that I care about something like serverless then it gives me all serverless articles even if I also said I care about JavaScript/Node

**Comment by idoshamun** [comment]
Ok, I totally understand now. Let me get back to you on this one.

**Comment by idoshamun** [comment]
After discussing with the team, we understand the issue you raised and thought about it carefully. Unfortunately, the solution you suggest might create major conflicts in content filtering and different users might expect different behavior from this feature. We have other ideas to make sure you get only relevant content. I hope you understand.
