### ISSUE TITLE
Feature Request: Bookmark by tag

### ISSUE THREAD

**Issue by dryleaf** [dailynowco/daily#56]
#### Feature Suggestion
- Bookmark by tag

**Details**
- create tag/folder
- bookmarks can be stored or organized by `tag` or inside a `folder`
- drag / move / change `tag / folder` of → bookmark

**Relevance**
- To easily save topics of interests

**Comment by idoshamun** [comment]
@dryleaf, thanks for submitting this feedback :)

We understand that you might have a problem finding the bookmark you were looking for.
I have a few questions to understand you situation and come up with a good solution:
1. How many bookmarks do you currently have? (approx.)
2. Do you think that more advanced filtering on your bookmarks, such as search, might do the work as well?
