### ISSUE TITLE
Feature Request: Exclude articles that need premium accounts

### ISSUE THREAD

**Issue by trojano31** [dailynowco/daily#57]
#### Feature Suggestion

I'd love to have a simple switch that would enable/disable *premium* articles or at least mark them as paid ones. I'm talking mainly about Medium members' articles: https://medium.com/membership

**Comment by idoshamun** [comment]
Hi @trojano31,

You are totally right, we don't believe in premium and think content should be free for all.
I have an initial solution to filter out all premium content, hopefully I will finalize it soon.

Please bare with us and thank you for reaching out :)

**Comment by idoshamun** [comment]
As of today, every content which will be detected as paywall content will be ignored and you will not see it.

**Comment by trojano31** [comment]
Awesome! Keep up the good work!
