### ISSUE TITLE
 New Tab Load data from Local Storage

### ISSUE THREAD

**Issue by vishalksuthar** [dailynowco/daily#59]
#### Feature Suggestion
When we click on "New Tab" then every time page will load from Daily  live server so that impact on loading performance and take longer time to load. 
I want to load from local storage while is load earlier in sytem, If have any new update then load after few minutes or second and also you can give refresh button . 

Short information Note* : I want to when i click on new tab then i don't want loading screen .

**Comment by idoshamun** [comment]
Hi @vishalksuthar,

Thanks for reaching out and submitting your idea :)
As soon as Daily opens it load everything from local cache and only when idle it requests to fetch all the new information from the server.
Please specify what loading screen you refer to so I can understand what the problem exactly is.

**Comment by vishalksuthar** [comment]
When I click on New tab , Bellow blank & Black screen showing for 10-15 seconds , After that showing /* news for you */ screen. like second image.

![image](https://user-images.githubusercontent.com/43471370/62279736-4cd2e980-b468-11e9-8ab5-8612229f675f.png)

Default home page
![image](https://user-images.githubusercontent.com/43471370/62279790-63794080-b468-11e9-8940-a941af7abcea.png)

**Comment by idoshamun** [comment]
So weird it should not take this long to see the title (for me it takes less than a second). The initial load time has nothing to do with the server because it fetches everything from local storage.
Maybe we have some performance issues that need to be fixed. I will have to dig deeper.

**Comment by vishalksuthar** [comment]
> 
> 
> So weird it should not take this long to see the title (for me it takes less than a second). The initial load time has nothing to do with the server because it fetches everything from local storage.
> Maybe we have some performance issues that need to be fixed. I will have to dig deeper.

My Browser Info 

Name 	Firefox
Version 	69.0b9
Build ID 	20190730004747
Update Folder 	
C:\ProgramData\Mozilla\updates\CA9422711AE1A81C
Update History 	
Update Channel 	aurora
User Agent 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
OS 	Windows_NT 10.0
Application Binary 	C:\Program Files\Firefox Developer Edition\firefox.exe
Profile Folder 	
C:\Users\Vishal\AppData\Roaming\Mozilla\Firefox\Profiles\32uqvv1t.dev-edition-default
Enabled Plugins 	about:plugins
Build Configuration 	about:buildconfig
Memory Use 	about:memory
Performance 	about:performance
Registered Service Workers 	about:serviceworkers
Launcher Process 	Enabled
Multiprocess Windows 	1/1 Enabled by default
Remote Processes 	10
Enterprise Policies 	Inactive
Google Location Service Key 	Found
Google Safebrowsing Key 	Found
Mozilla Location Service Key 	Found
Safe Mode 	false
Profiles 	about:profiles

**Comment by idoshamun** [comment]
Thank you for sharing this information!
I have just released a new version 2.1.4, should be available soon in the stores.
This version reduces drastically the initial bundle size and should also improve load time performance.
I found a performance bottleneck in one of the components. Please check this version and let me know

**Comment by vishalksuthar** [comment]
Welcome Ido,  Thanks for quick update.
Yes now it's working manageable fine.  Now it's taking only few seconds for loading.

**Comment by idoshamun** [comment]
You welcome :)
Could you please send your PC spec?


---- On Sat, 03 Aug 2019 11:24:16 +0300 notifications@github.com wrote ----



Welcome Ido, Thanks for quick update.
Yes now it's working manageable fine. Now it's taking only few seconds for loading.

**Comment by vishalksuthar** [comment]
Sure. Please find in attachments.
[Browserinfo.txt](https://github.com/dailynowco/daily/files/3463535/Browserinfo.txt)

[system_spec.txt](https://github.com/dailynowco/daily/files/3463537/system_spec.txt)

**Comment by vishalksuthar** [comment]
Now it's working pretty nice.

**Comment by idoshamun** [comment]
After reinstalling the extension?

**Comment by vishalksuthar** [comment]
Reinstall firefox and extension as well as.

**Comment by idoshamun** [comment]
Glad to hear it works well! :1st_place_medal:  I'm closing the issue if you don't mind.
