### ISSUE TITLE
Web layout is not responsive below 1024px

### ISSUE THREAD

**Issue by sigfriedseldeslachts** [dailynowco/daily#6]
#### Bug Report

Explanation: As the title says the layout it not responsive. Not really of a big issue but kinda annoying when you have multiple windows open on a screen next to each other (you know multi task mode).

Reproduce: none

Version: 1.2.2

Browser version: Chrome 64.0.3282.167

OS: Win (10.0.16299 Build 16299) & Ubuntu 16.04

Image:
![image](https://user-images.githubusercontent.com/15171357/36339953-8827e51a-13d0-11e8-9366-f3c1a68c06da.png)

### Feedback
Nice app. Keep it up!

**Comment by idoshamun** [comment]
Hi @sigfriedseldeslachts,

First of all, thank you for your valuable feedback.
As of today the minimum width supported by Daily is `1024px`, if your window is  smaller you might see the "not responsive layout".
Let me know if your window is bigger and you still experience this issue.

Anyway, we should rethink the minimum resolution to better support multi task mode.

**Comment by sigfriedseldeslachts** [comment]
Yeah, it works when my windows is fullscreen. Not a real problem just kinda annoying.

**Comment by idoshamun** [comment]
Hi @sigfriedseldeslachts, Daily 2.0 is out and it is much more responsive than before. Feel free to check it out, minimum width is around 750px now

**Comment by idoshamun** [comment]
@all-contributors please add @sigfriedseldeslachts for bug
