### ISSUE TITLE
Improve "Download" link preview in social media

### ISSUE THREAD

**Issue by Ornataweaver** [dailynowco/daily#7]
Make it have preview so it would spread better on Social Media. ;)

**Comment by Ornataweaver** [comment]
check https://twitter.com/Ornataweaver/status/976485066942681089.

**Comment by Ornataweaver** [comment]
It's strange, I checked it and there is preview.

**Comment by Ornataweaver** [comment]
Can I delete this issue? Or should I just close it?

**Comment by idoshamun** [comment]
@Ornataweaver actually it is not our preview, I think it's google chrome store preview. We should create our own preview. So let's just leave it open until we update the preview. Thanks for idea!

**Comment by Ornataweaver** [comment]
Setting desirable previews for links is one of the most important things on the web at this era. I also want a guide on this matter, so people make better previews, thus a higher quality of web!
I'm linking this to Enlight project. https://enlight.nyc/
https://github.com/TryEnlight/tryenlight.github.io/issues/2

**Comment by Ornataweaver** [comment]
@shamdasani what say you?

**Comment by Ornataweaver** [comment]
#IDEAsPlatform
This one is a Vision of my Life. the dots will be connected later.
Thanks for letting me brainstorm here.

**Comment by idoshamun** [comment]
Finally I had time to tackle this issue correctly and I ended up redirecting bots to our landing page, this way we will get the best looking preview in social media.
It might take a day or two for the social platforms to invalidate their cache but this issue is done!

**Comment by idoshamun** [comment]
@all-contributors please add @Ornataweaver for ideas
