### ISSUE TITLE
Feature Request: Add Grab & Drag like scrolling experience!!

### ISSUE THREAD

**Issue by Droyk** [dailynowco/daily#75]
Just like in mobile. we grab and drag the page to scroll. 

https://ilyashubin.github.io/scrollbooster/

**Comment by idoshamun** [comment]
Thanks @Droyk for sharing your ideas with us :)
I would like to kindly ask what is the motivation for such feature as this UX pattern is not pretty common in desktop webapp

**Comment by Droyk** [comment]
Scrolling with the wheel is tiring. I have been using grab & drag scrolling for the previous 6 months & believe me when I say it's relaxingly efficient than the default wheel or scrollbar. 

I mean on the mobile. how many times have you used the scrollbar for scrolling the page? never, right. it's slow, inefficient & hard to grab. for big screens like desktop, it makes sense but still slow & not so smooth experience as compare to grab & drag. this feature is not necessary but would be a great enhancement to this extension & you know users love options. I don't know if I can call this a motivation but still something :)

**Comment by idoshamun** [comment]
Totally get your point! Thank you for dedicating the time explaining it.
Let me take it back and discuss with @tsahimatsliah.

**Comment by idoshamun** [comment]
After an internal discussion, we believe adding this scrolling mechanism might conflict a future draggable gesture. I hope you understand :)

**Comment by Droyk** [comment]
>a future draggable gesture.

Possible to elaborate?

**Comment by idoshamun** [comment]
Not sure if I understand how drag based scrolling can work side by side with for example order bookmarks by dragging the card. Would appreciate your feedback

**Comment by Droyk** [comment]
>order bookmarks by dragging the card. Would appreciate your feedback

look I'm not a developer Just an enthusiast. so I won't be able to provide you with a technical explanation but in a laymen terms, you can add grab and drag rejection for certain elements of the page. so like you said if you want to order a bookmark by dragging the card you can do that by adopting grab & drag rejection. just imagine if you are in mobile space of UX how it would pan out? I know it is difficult but definitely not impossible.

**Comment by idoshamun** [comment]
First of all thank you for baring with me. Actually I didn't know we have non-developer users :wink:
I didn't mean technical explanation but UX explanation as you just provided. Still doubting, will let you know

**Comment by idoshamun** [comment]
Unfortunately, we decided not to proceed with developing this feature as it will probably cause UX issues. Thank you for baring with us, feel free to share more ideas :)
