### ISSUE TITLE
Post Searching or Tag Search bar

### ISSUE THREAD

**Issue by vishalksuthar** [dailynowco/daily#76]
#### Feature Suggestion
Dear, I want to Search bar on top of menu or anywhere else. 
Using search bar:
1. I can able to search post.
2. I can able to search #<MY_Request_Tag> post.
3. Search news

**Comment by idoshamun** [comment]
Thank you @vishalksuthar for another great idea!
Search functionality is indeed in our backlog but unfortunately not in the near future.
Stay tuned!

**Comment by vishalksuthar** [comment]
Dear Can we go with attached searchbar design
![SearchBar](https://user-images.githubusercontent.com/43471370/62846627-3db52c80-bcef-11e9-8e53-f88d8609e4cd.png)

**Comment by idoshamun** [comment]
Thanks for sharing the design. This is actually for @tsahimatsliah to decide but at first sight it looks like it doesn't comply with our design guidelines.

**Comment by vishalksuthar** [comment]
This in only idea ,.
Steps;
1. Click on search icon.
2. Then search bar open and user can search request content like #<Tag>,Post etc.

![SearchBar](https://user-images.githubusercontent.com/43471370/62851240-17998780-bd03-11e9-9a5c-837f5e5aa82b.png)
May be like
