### ISSUE TITLE
Allow users to edit amount of items shown in Grid View. 

### ISSUE THREAD

**Issue by TxsAdamWest** [dailynowco/daily#79]
#### Feature Suggestion

*Describe your feature and explain why you need it*
It would be nice to be able to control the amount of items that show up when in grid view.  I really like this extension but feel on larger resolutions, there's simply too many items to look at every time I open a tab.  I'd like to be able to concentrate on a select number of them to de-clutter the welcome screen.  

#### Bug Report

Explanation: *Describe the bug as accurate as possible*
Please see screenshot.  
![dailynow_feature_request_2](https://user-images.githubusercontent.com/16004559/62789567-ce410200-ba8e-11e9-9a9f-e605fc4498df.png)

Reproduce: *Steps to reproduce the bug, if you know them*
Just open a new tab. :)

Version: *Daily version (can be found in Chrome's extension page)*
2.1.4

Browser version: *Your browser version*
Chrome 76.0.3809.100 (Official Build) (64-bit)

OS: *Your operating system including version*
Windows 10

*Please add screenshots if possible or any other information that can help fixing the bug*

**Comment by idoshamun** [comment]
Thank you @TxsAdamWest for such an awesome idea!
Not sure about the exact UI implementation but @tsahimatsliah will take care of it :stuck_out_tongue_winking_eye:

**Comment by idoshamun** [comment]
It took a while but we had to make sure we perfect this idea.
You are welcome to check out the issue and the design:
https://github.com/dailynowco/daily-apps/issues/52

**Comment by idoshamun** [comment]
@all-contributors please add @TxsAdamWest for ideas

**Comment by TxsAdamWest** [comment]
![daily](https://user-images.githubusercontent.com/16004559/70073184-07f9c380-15be-11ea-9b3e-f8913956c2fa.png)

Beautiful.  Great implementation guys. :)

**Comment by idoshamun** [comment]
Thank you deeply :hugs:
