### ISSUE TITLE
Header overlap on previous post  on  insane mode  of news for you

### ISSUE THREAD

**Issue by vishalksuthar** [dailynowco/daily#80]
#### Bug Report
Header hide because of overlap into previous post , please find the screenshots.
![image](https://user-images.githubusercontent.com/43471370/62915066-a57f7c00-bdb0-11e9-85b5-25749ea58f44.png)
Img-2
![image](https://user-images.githubusercontent.com/43471370/62915101-cba51c00-bdb0-11e9-938f-a793cd764b4a.png)
Img-3
![image](https://user-images.githubusercontent.com/43471370/62915147-f8f1ca00-bdb0-11e9-9dc9-ca82560c20f3.png)

**Comment by idoshamun** [comment]
@vishalksuthar thank you very much for reporting this bug and dedicating time to improve Daily.
This bug is reported here: https://github.com/dailynowco/daily-apps/issues/25 with some implementation hints.
Hopefully I will get to it soon and fix it

**Comment by vishalksuthar** [comment]
Actually I don't know about you already opened this issue.

**Comment by idoshamun** [comment]
It's perfectly fine!

**Comment by idoshamun** [comment]
@allcontributors add @vishalksuthar for bug

**Comment by idoshamun** [comment]
This issue is now fixed, should be released in v2.1.9.
Currently we are having some issues with Chrome Store so it might be delayed a bit but it's already available on Firefox.
