### ISSUE TITLE
timestamp in notifications popup

### ISSUE THREAD

**Issue by zvikarp** [dailynowco/daily#86]
#### Bug Report

Explanation: Could be nice if the timestamp would also have a date, not only a time. Also just noticed that if the user is offline the timestamp is displayed `[object object]`.

Version: 2.1.4
Browser version: Google Chrome, Version 76.0.3809.100 (Official Build) (64-bit)

**Comment by idoshamun** [comment]
Hi @ZviKarp,

Thank you very much for reaching out and reporting this issue :)
I will try to reproduce this issue and proceed with fixing it.

Regarding the date, I believe you are right and we will add it as well.
