### ISSUE TITLE
firefox extension showing welcome eachtime i open a new tab

### ISSUE THREAD

**Issue by justnewbee** [dailynowco/daily#87]
Explanation:

firefox extension version 2.4.0 gives welcome page every time, i have done 'got it' for many times, and restarted firefox for many times

it is new today

Reproduce:

open a new tab

Version: 2.4.0

Browser version: Firefox Developer Edition 69.0b15 

OS: Mac

![image](https://user-images.githubusercontent.com/2276086/63485068-92695c00-c4d4-11e9-81f5-d25cdfeacccd.png)

**Comment by imeteora** [comment]
Yes, I have this issue too. Browser: Firefox Developer Edtion 69.0b15 (64-bit)

**Comment by idoshamun** [comment]
Hi everyone, thanks for reporting this critical issue.
This is probably caused by some changes we did for version 2.4.0. I will check it as soon as possible.

**Comment by idoshamun** [comment]
I released v2.4.1 which suppose to fix this issue (honestly speaking I wasn't able to reproduce on my local machine). Please let me know how it works :)

**Comment by idoshamun** [comment]
@justnewbee @imeteora could you please confirm the bug is resolved?

**Comment by imeteora** [comment]
Thanks a lot. the issue is DONE.
