### ISSUE TITLE
Feature Suggestion: Let the users remove items from the grid

### ISSUE THREAD

**Issue by OHeimlich** [dailynowco/daily#88]
#### Feature Suggestion
Hi,

I have Daily for a while and it's great, thanks!

I suggest to let the user the ability to remove items that doesn't interest him in the grid.

You can keep the removed items and maybe later on let the user hints on which tags will be more relevant for him.

I'll like to try and implement it but will need a bit guideline.

**Comment by idoshamun** [comment]
Hi @OHeimlich,

First of all thank you for using Daily and sharing your ideas :)
I actually relate to your suggestion and think it might be beneficial to Daily's users.
It is a good timing for such suggestions now that we are working on refactoring our feed query mechanism (please refer to https://github.com/dailynowco/daily-api/issues/22). Once done we can proceed with implementing this and of course we would love to guide you through your first contribution which would be awesome for sure :rocket:

**Comment by idoshamun** [comment]
Glad to share that following this PR https://github.com/dailynowco/daily-api/pull/27, now every post that you will report as broken link or NSFW will be removed from your feed. Though, it will be shown only after you refresh. Next release of the application shall include also a standalone "Hide" option and immediately should remove the post.

**Comment by idoshamun** [comment]
This feature is released in v2.5.0

**Comment by PiterGoCompany** [comment]
I've got 2.12.2 version and I can't find 'hide' option.

**Comment by PiterGoCompany** [comment]
> I've got 2.12.2 version and I can't find 'hide' option.

After signing in option is available :), so problem has been resolved.
