### ISSUE TITLE
Some listed news sources don't have any articles yet 

### ISSUE THREAD

**Issue by DarkMannn** [dailynowco/daily#93]
Some news sources, like JavaScript weekly and Node.js weekly for example, don't have any articles yet on your platform, but they are listed as available sources.

I just want to check is this only happening to me maybe?
If not, then can we expect articles from those sites to appear any time soon?

**Comment by idoshamun** [comment]
Hi @DarkMannn,

Thank you for reporting about this issue.
I've just checked both JavaScript weekly and Node.js weekly and they both contain articles.
Could you please try again?

**Comment by DarkMannn** [comment]
Thank you for responding @idoshamun,

I just discovered that this happens only when I'm signed in. When I'm logged out and using the app, both JavaScript and Node weekly work properly.
My email was already subscribed to their regular newsletters, is it possible that this is the cause of the problem?

I've unsubscribed now, but the result is the same... maybe I need to wait some time for the subscription list to get updated (just guessing).

**Comment by idoshamun** [comment]
Thank you for investigating further, I believe I know the reason for the bug now.
I'll work to solve it ASAP and let you know when it's done.
Most probably is that your personal filters (favorite publications and tags) are applied even to the single publication page.
This happens because of a recent change we applied to the feed mechanism.

**Comment by idoshamun** [comment]
@DarkMannn could you please confirm that the issue is now solved?

**Comment by DarkMannn** [comment]
@idoshamun Yeah... everything works now. Thank you for fixing this!

**Comment by idoshamun** [comment]
@all-contributors please add @DarkMannn for bug
