### ISSUE TITLE
Suggestion for header section

### ISSUE THREAD

**Issue by ugurozoz** [dailynowco/daily#94]
#### Feature Suggestion

Hello,
when i use  daily, i realized that sometimes while i scrolling page somehow i want to switch to personal bookmarks section. Unfortunately when this happen, header section does not be reachable. Sometimes i have to scroll too much to top of page to see that button.  i think that kind development might be useful for user experience. By the way as a front-end developer i can help on this.

**Comment by idoshamun** [comment]
Hi @ugurozoz,

Thanks for reaching out, I would like to clarify what header section you are referring to. Could you send please a screenshot of this header? Because there is Chrome's header with the bookmarks and there is also our header with Daily's bookmarks.

**Comment by ugurozoz** [comment]
hi @idoshamun, 
Sorry for mising information. I mentioned Daily's custom bookmarks section. Which is we use to save articles, for read later.  I added an screenshot link about issue, i hope it helps.  
https://imge.to/i/v44HTY

**Comment by ugurozoz** [comment]
Here is my solution,
I fixed the header so it stands still when page scrolls. 
https://youtu.be/wvOMSvb1gh4

**Comment by idoshamun** [comment]
Thank you @ugurozoz for providing all the information and dedicating the time.
Let me consult with @tsahimatsliah about the possible solutions.

**Comment by ugurozoz** [comment]
Thanks in advance @idoshamun ,
best regards

**Comment by idoshamun** [comment]
Unfortunately, sticking the header to the top interferes with some of our near-future features (such as https://github.com/dailynowco/daily-apps/issues/52).  Hopefully, you understand the situation.
