### ISSUE TITLE
Top sites are blocking my nav bar

### ISSUE THREAD

**Issue by SergioFaya** [dailynowco/daily#96]
#### Bug Report

Explanation: After I signed in using Github (if that can be the cause of the bug), I detected that a social network section is blocking part of my nav bar including half of the Github icon.

Reproduce: I have not found any way to reproduce it.

Version: 2.0

Browser version: 76.0.3809.132

OS: Ubuntu 14.04 LTS

![image](https://user-images.githubusercontent.com/15983833/65519492-4e5be380-dee6-11e9-92e5-fac5582a5ae8.png)

**Comment by SergioFaya** [comment]
If it can be helpfull in any way here it is the html of the social media tag:

`<div class="instructions invert"><div class="instructions__top-sites"><div class="header__top-site"><img src="https://app.dailynow.co/icon?url=https%3A%2F%2Fwww.google.com%2F&amp;size=20" class="top-site__image"></div><div class="header__top-site"><img src="https://app.dailynow.co/icon?url=https%3A%2F%2Fweb.whatsapp.com%2F&amp;size=20" class="top-site__image"></div><div class="header__top-site"><img src="https://app.dailynow.co/icon?url=https%3A%2F%2Fwww.youtube.com%2F&amp;size=20" class="top-site__image"></div><div class="header__top-site"><img src="https://app.dailynow.co/icon?url=https%3A%2F%2Fwww.twitter.com%2F&amp;size=20" class="top-site__image"></div><div class="header__top-site"><img src="https://app.dailynow.co/icon?url=https%3A%2F%2Fwww.facebook.com%2F&amp;size=20" class="top-site__image"></div></div><div class="instructions__desc">
      Should we show your recently visited sites?
    </div><div class="instructions__buttons"><button class="btn btn-invert">
        No
      </button><button class="btn btn-invert">
        Yes
      </button></div></div>`

**Comment by idoshamun** [comment]
Hi @SergioFaya,
Thank you for using Daily and reporting this issue.
We have already fixed this issue and will publish a fix soon

**Comment by idoshamun** [comment]
Fix is now available in store

**Comment by idoshamun** [comment]
@all-contributors please add @SergioFaya for bugs
